### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by anitaa1990** [Android-File-Share/FileShare#2]
Hey, I keep getting the following error when trying to connect to receiver:

`01-09 07:36:13.039 8035-8819/io.github.karuppiah7890.filesharer W/System.err: java.net.ConnectException: Connection refused
01-09 07:36:13.039 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
01-09 07:36:13.039 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:343)
01-09 07:36:13.039 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:205)
01-09 07:36:13.040 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:187)
01-09 07:36:13.040 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
01-09 07:36:13.040 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.Socket.connect(Socket.java:586)
01-09 07:36:13.040 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.Socket.connect(Socket.java:535)
01-09 07:36:13.040 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.Socket.<init>(Socket.java:427)
01-09 07:36:13.040 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at java.net.Socket.<init>(Socket.java:243)
01-09 07:36:13.040 8035-8819/io.github.karuppiah7890.filesharer W/System.err:     at io.github.karuppiah7890.fileshare.SenderThread.run(SenderThread.java:43)`

**Comment by karuppiah7890** [comment]
I think you started the sender before starting the receiver.

**Comment by anitaa1990** [comment]
Actually i clicked on get file. Then a new code is generated and this new code i add to sender. Then I get connecting and then this exception

**Comment by karuppiah7890** [comment]
Not sure. Gotta check on the code. But have you checked the example app I provided ? Or you get this exception in that app only ?

**Comment by anitaa1990** [comment]
Yup using the same app from github. Just cloned and built and got this error

**Comment by karuppiah7890** [comment]
I don't know. It's been long since I worked on this
